[tool.poetry]
name = "fast-api-micro-service-template"
version = "1.1.0"
description = "A Cookiecutter template for spinning up a micro service"
authors = ["Max Pfeiffer <max.pfeiffer@maxpfeiffer.ch>"]

[tool.poetry.dependencies]
python = "3.9.*"

[tool.poetry.dev-dependencies]
cookiecutter = "2.1.1"
pytest = "7.1.3"
pytest-cookies = "0.6.1"
black = "22.8.0"
pre-commit = "2.17.0"
docker = "6.0.0"
httpx = "0.23.0"
furl = "2.1.3"

# https://docs.pytest.org/en/latest/reference/customize.html
[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.black]
line-length = 80
target-version = ['py39']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
