[tool.poetry]
name = "fast-api-micro-service-template"
version = "1.1.0"
description = "A Cookiecutter template for spinning up a micro service"
authors = ["Max Pfeiffer <max.pfeiffer@maxpfeiffer.ch>"]

[tool.poetry.dependencies]
python = "3.11.*"

[tool.poetry.dev-dependencies]
cookiecutter = "2.5.0"
pytest = "7.4.3"
pytest-cookies = "0.7.0"
black = "23.12.0"
pre-commit = "3.6.0"
docker = "7.0.0"
httpx = "0.25.2"
furl = "2.1.3"

# https://docs.pytest.org/en/latest/reference/customize.html
[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.black]
line-length = 80
target-version = ['py311']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
